#!/bin/bash

echo "🚨 IMMEDIATE PRODUCTION FIX - Run this NOW on your server!"
echo ""
echo "SSH into your server and run these commands EXACTLY:"
echo ""
echo "# 1. Enter container"
echo "docker exec -it optyshop-backend bash"
echo ""
echo "# 2. Go to app directory"  
echo "cd /app"
echo ""
echo "# 3. Run immediate database fix"
echo "npx prisma db execute --stdin << 'SQL'"
echo "ALTER TABLE banners ADD COLUMN page_type ENUM('home', 'category', 'subcategory', 'sub_subcategory') NOT NULL DEFAULT 'home';"
echo "ALTER TABLE banners ADD COLUMN category_id INTEGER NULL;"
echo "ALTER TABLE banners ADD COLUMN sub_category_id INTEGER NULL;"
echo "SQL"
echo ""
echo "# 4. Regenerate Prisma Client"
echo "npx prisma generate"
echo ""
echo "# 5. Exit container"
echo "exit"
echo ""
echo "# 6. Restart container"
echo "docker restart optyshop-backend"
echo ""
echo "✅ This will fix the error immediately!"
